// <auto-generated />
using System;
using Cdsqg.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cdsqg.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008164528_AnnualReportingOnly")]
    partial class AnnualReportingOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cdsqg.Core.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPersons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanFiles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.AgencyTaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentFileUrls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CalculatedStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CompletionPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Deliverables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GoalTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastReportedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("LatestProgressValue")
                        .HasColumnType("numeric");

                    b.Property<string>("LatestQualitativeStatus")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SummaryNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("AssignedAgencyId");

                    b.HasIndex("GoalTaskId", "AgencyId")
                        .IsUnique();

                    b.ToTable("AgencyTaskExecutions");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.DataImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalGoalsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTasksCreated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DataImportLogs");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentFilePaths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signer")
                        .HasColumnType("text");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TimeResolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.GoalTaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyDeliverables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("AssignedAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoordinatingAgencyIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomBaseline")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Deliverables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DynamicKPIs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EvaluationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<bool>("IsGeneralTask")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LeadAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgencyId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LeadAgencyId");

                    b.HasIndex("UnitId");

                    b.ToTable("GoalTaskItems");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByAgencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DraftingAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DraftingAgencyName")
                        .HasColumnType("text");

                    b.Property<string>("EffectStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("IssuingAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuingAgencyName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("SignerName")
                        .HasColumnType("text");

                    b.Property<string>("SignerTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentFileUrls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CalculatedAlert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("CalculatedProgressPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Deliverables")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GoalTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<string>("QualitativeStatus")
                        .HasColumnType("text");

                    b.Property<decimal?>("QuantitativeValue")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SummaryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("GoalTaskId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.TargetBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalTaskId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCustomOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("OverrideNote")
                        .HasColumnType("text");

                    b.Property<string>("TargetQualitativeStatus")
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GoalTaskId", "Year")
                        .IsUnique();

                    b.ToTable("TargetBaselines");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.TaskUrgeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForecastDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GoalTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GoalTaskItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeadAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientsSummary")
                        .HasColumnType("text");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("UrgeContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalTaskItemId");

                    b.HasIndex("LeadAgencyId");

                    b.ToTable("TaskUrgeLogs");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.UnitDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Agency", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "ParentAgency")
                        .WithMany("ChildAgencies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAgency");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.AgencyTaskExecution", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdsqg.Core.Entities.Agency", "AssignedAgency")
                        .WithMany()
                        .HasForeignKey("AssignedAgencyId");

                    b.HasOne("Cdsqg.Core.Entities.GoalTaskItem", "GoalTaskItem")
                        .WithMany("AgencyExecutions")
                        .HasForeignKey("GoalTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("AssignedAgency");

                    b.Navigation("GoalTaskItem");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.GoalTaskItem", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "AssignedAgency")
                        .WithMany()
                        .HasForeignKey("AssignedAgencyId");

                    b.HasOne("Cdsqg.Core.Entities.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdsqg.Core.Entities.Agency", "LeadAgency")
                        .WithMany()
                        .HasForeignKey("LeadAgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdsqg.Core.Entities.UnitDictionary", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAgency");

                    b.Navigation("Document");

                    b.Navigation("LeadAgency");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Notification", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cdsqg.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Agency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.ProgressLog", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.HasOne("Cdsqg.Core.Entities.GoalTaskItem", "GoalTaskItem")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("GoalTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("GoalTaskItem");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.TargetBaseline", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.GoalTaskItem", "GoalTaskItem")
                        .WithMany("Baselines")
                        .HasForeignKey("GoalTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalTaskItem");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.TaskUrgeLog", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.GoalTaskItem", "GoalTaskItem")
                        .WithMany()
                        .HasForeignKey("GoalTaskItemId");

                    b.HasOne("Cdsqg.Core.Entities.Agency", "LeadAgency")
                        .WithMany()
                        .HasForeignKey("LeadAgencyId");

                    b.Navigation("GoalTaskItem");

                    b.Navigation("LeadAgency");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.User", b =>
                {
                    b.HasOne("Cdsqg.Core.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Agency", b =>
                {
                    b.Navigation("ChildAgencies");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.Document", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cdsqg.Core.Entities.GoalTaskItem", b =>
                {
                    b.Navigation("AgencyExecutions");

                    b.Navigation("Baselines");

                    b.Navigation("ProgressLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
