export { createApp, h, ref, nextTick, withDirectives } from 'vue';
export { default as FloatingVue } from 'floating-vue';
export { default as Dashboard } from '../src/views/ExecutiveDashboard.vue';
export { default as Document } from '../src/views/DocumentDetailView.vue';
export { authState } from '../src/services/auth';
export { accessibleDialog } from '../src/directives/accessibleDialog';
export { accessibleData } from '../src/directives/accessibleData';
export { loadExcelReader, loadExcelWriter } from '../src/utils/excelRuntime';
export { default as AnnualBaseline } from '../src/components/BaselineOverrideModal.vue';
export { default as AnnualProgress } from '../src/components/ProgressUpdateModal.vue';
export { default as Reports } from '../src/views/ExecutiveReportsView.vue';
